#!/usr/bin/env bash
# Compute real completion metrics from the repo state and write
# site/_data/progress.yml. Run manually or from the deploy workflow
# before `jekyll build`.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/site/_data/progress.yml"
mkdir -p "$(dirname "$OUT")"

# CSV row counts (exclude header)
count_csv_rows() {
  local f="$1"
  [ -f "$f" ] || { echo 0; return; }
  local n
  n=$(wc -l < "$f")
  echo $(( n > 0 ? n - 1 : 0 ))
}

PHOTOS=$(count_csv_rows "$ROOT/data/photographs.csv")
PHOTOGRAPHERS=$(count_csv_rows "$ROOT/data/photographers.csv")
SECTIONS=$(count_csv_rows "$ROOT/data/sections.csv")

# File counts
SOURCES=$(find "$ROOT/sources" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
SECTION_ARTICLES=$(find "$ROOT/site/_sections_articles" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
PHOTOGRAPHER_ARTICLES=$(find "$ROOT/research/photographers" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')

# Target totals from primary scholarship
TOTAL_PHOTOS=503
TOTAL_PHOTOGRAPHERS=273

PHOTOS_PCT=$(( PHOTOS * 100 / TOTAL_PHOTOS ))
PHOTOGRAPHERS_PCT=$(( PHOTOGRAPHERS * 100 / TOTAL_PHOTOGRAPHERS ))

cat > "$OUT" <<YAML
# Generated by scripts/compute_progress.sh — do not edit directly.
# Used by site/index.md to render live completion strips on each tile.

exhibition:
  kind: status
  label: "substantive"
  note: "Substantive overview merged via PR #41 (24 January – 8 May 1955 MoMA opening; Steichen + Wayne Miller; Paul Rudolph installation; Sandburg prologue; arc of the show; reception thread)."

photographs:
  kind: count
  count: ${PHOTOS}
  total: ${TOTAL_PHOTOS}
  pct: ${PHOTOS_PCT}
  label: "${PHOTOS} / ${TOTAL_PHOTOS}  ·  ${PHOTOS_PCT}%"

photographers:
  kind: count
  count: ${PHOTOGRAPHERS}
  total: ${TOTAL_PHOTOGRAPHERS}
  articles: ${PHOTOGRAPHER_ARTICLES}
  pct: ${PHOTOGRAPHERS_PCT}
  label: "${PHOTOGRAPHERS} / ${TOTAL_PHOTOGRAPHERS}  ·  ${PHOTOGRAPHERS_PCT}%  ·  ${PHOTOGRAPHER_ARTICLES} bios"

sections:
  kind: count
  count: ${SECTION_ARTICLES}
  total: ${SECTIONS}
  pct: 100
  label: "${SECTION_ARTICLES} cluster articles  ·  working reconstruction"

tour:
  kind: status
  label: "substantive"
  note: "Substantive overview merged via PR #47 (1955-56 US 6-city tour; USIA international tour 1955-c.1962/1964/1965; Corcoran/Guatemala/Tokyo/Johannesburg/Moscow venues attested; 1992-94 second wave Toulouse/Tokyo/Hiroshima; Cold War cultural-diplomacy framing). Headline aggregate (9M/91/37) pending NARA RG 306."

clervaux:
  kind: status
  label: "substantive"
  note: "Substantive overview merged via PR #43 (1964-66 donation; 1974-89 partial display; 1994 permanent installation; September 2010 → July 2013 second restoration with Studio Berselli + NJOY rooms; current CNA curation)."

unesco:
  kind: status
  label: "substantive"
  note: "Substantive overview merged via PR #45 (1992 Memory of the World programme; IAC + Executive Board pathway; 2002 submission by Luxembourg, 2003 inscription; 32-themes register count; 1992-94 pre-inscription touring; what inscription does and does not entail)."

reception:
  kind: status
  label: "substantive"
  note: "Substantive overview merged via PR #27 (Barthes 1957, Sontag 1977, Sekula 1981, Sandeen 1995, Stimson 2006, Turner 2013 framework). Tier 1-2 critical anchors in place; full critical-reception article."

bibliography:
  kind: count
  count: ${SOURCES}
  label: "${SOURCES} source entries  ·  growing"

mindmap:
  kind: status
  label: "live"
  note: "Continuously updated."
YAML

echo "wrote $OUT"
echo "  photographs: ${PHOTOS}/${TOTAL_PHOTOS} (${PHOTOS_PCT}%)"
echo "  photographers: ${PHOTOGRAPHERS}/${TOTAL_PHOTOGRAPHERS} (${PHOTOGRAPHERS_PCT}%) + ${PHOTOGRAPHER_ARTICLES} bios"
echo "  sections: ${SECTION_ARTICLES} cluster articles (${SECTIONS} rows)"
echo "  sources: ${SOURCES} entries"
