#!/usr/bin/env bash
# Compute real completion metrics from the repo state and write
# site/_data/progress.yml. Run manually or from the deploy workflow
# before `jekyll build`.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/site/_data/progress.yml"
mkdir -p "$(dirname "$OUT")"

# CSV row counts (exclude header)
count_csv_rows() {
  local f="$1"
  [ -f "$f" ] || { echo 0; return; }
  local n
  n=$(wc -l < "$f")
  echo $(( n > 0 ? n - 1 : 0 ))
}

PHOTOS=$(count_csv_rows "$ROOT/data/photographs.csv")
PHOTOGRAPHERS=$(count_csv_rows "$ROOT/data/photographers.csv")
SECTIONS=$(count_csv_rows "$ROOT/data/sections.csv")

# File counts
SOURCES=$(find "$ROOT/sources" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
SECTION_ARTICLES=$(find "$ROOT/site/_sections_articles" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')
PHOTOGRAPHER_ARTICLES=$(find "$ROOT/research/photographers" -name "*.md" -type f 2>/dev/null | wc -l | tr -d ' ')

# Target totals from primary scholarship
TOTAL_PHOTOS=503
TOTAL_PHOTOGRAPHERS=273

PHOTOS_PCT=$(( PHOTOS * 100 / TOTAL_PHOTOS ))
PHOTOGRAPHERS_PCT=$(( PHOTOGRAPHERS * 100 / TOTAL_PHOTOGRAPHERS ))

cat > "$OUT" <<YAML
# Generated by scripts/compute_progress.sh — do not edit directly.
# Used by site/index.md to render live completion strips on each tile.

exhibition:
  kind: status
  label: "outline"
  note: "Placeholder — historian not yet dispatched."

photographs:
  kind: count
  count: ${PHOTOS}
  total: ${TOTAL_PHOTOS}
  pct: ${PHOTOS_PCT}
  label: "${PHOTOS} / ${TOTAL_PHOTOS}  ·  ${PHOTOS_PCT}%"

photographers:
  kind: count
  count: ${PHOTOGRAPHERS}
  total: ${TOTAL_PHOTOGRAPHERS}
  articles: ${PHOTOGRAPHER_ARTICLES}
  pct: ${PHOTOGRAPHERS_PCT}
  label: "${PHOTOGRAPHERS} / ${TOTAL_PHOTOGRAPHERS}  ·  ${PHOTOGRAPHERS_PCT}%  ·  ${PHOTOGRAPHER_ARTICLES} bios"

sections:
  kind: count
  count: ${SECTION_ARTICLES}
  total: ${SECTIONS}
  pct: 100
  label: "${SECTION_ARTICLES} cluster articles  ·  working reconstruction"

tour:
  kind: status
  label: "outline"
  note: "Placeholder — historian not yet dispatched."

clervaux:
  kind: status
  label: "outline"
  note: "Placeholder — historian not yet dispatched."

reception:
  kind: status
  label: "outline"
  note: "Major landmarks listed; essay pending."

bibliography:
  kind: count
  count: ${SOURCES}
  label: "${SOURCES} source entries  ·  growing"

mindmap:
  kind: status
  label: "live"
  note: "Continuously updated."
YAML

echo "wrote $OUT"
echo "  photographs: ${PHOTOS}/${TOTAL_PHOTOS} (${PHOTOS_PCT}%)"
echo "  photographers: ${PHOTOGRAPHERS}/${TOTAL_PHOTOGRAPHERS} (${PHOTOGRAPHERS_PCT}%) + ${PHOTOGRAPHER_ARTICLES} bios"
echo "  sections: ${SECTION_ARTICLES} cluster articles (${SECTIONS} rows)"
echo "  sources: ${SOURCES} entries"
